apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuhtreyt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yuhtreyt
  template:
    metadata:
      labels:
        app: yuhtreyt
    spec:
      containers:
      - image: okteto.dev/yuhtreyt:latest
        name: yuhtreyt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "9c9a2949-3c08-4433-b0db-fb5bdbe321f2"
        - name: Vless_Path
          value: "/vlfhfgtjt"
        - name: Vmess_UUID
          value: "9c9a2949-3c08-4433-b0db-fb5bdbe321f2"
        - name: Vmess_Path
          value: "/vm46563cgfdrd"
        - name: Share_Path
          value: "/v2link"
